import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "monthlybills (가제) — 내 구독과 고정비, 한 화면에",
  description:
    "구독과 월 고정비를 한 곳에서 추적하고, 결제일 알림까지 자동화합니다.",
>>>>>>> b8d83c31 (Add 프로젝트 한 줄 and 라우팅 — 상황별 읽을 md and 새 규칙·결정이 생겼을 때)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
<<<<<<< HEAD
      lang="en"
=======
      lang="ko"
>>>>>>> b8d83c31 (Add 프로젝트 한 줄 and 라우팅 — 상황별 읽을 md and 새 규칙·결정이 생겼을 때)
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
